# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c02077c129ec94ece8986d056007dfe"
name = "recomdo-ai"
application_url = "https://conventional-facing-donna-fan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "neosolax-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_markets,read_product_listings,read_products,read_publications,read_themes,write_customers,write_discounts,write_products,write_themes"

[auth]
redirect_urls = [
  "https://conventional-facing-donna-fan.trycloudflare.com/auth/callback",
  "https://conventional-facing-donna-fan.trycloudflare.com/auth/shopify/callback",
  "https://conventional-facing-donna-fan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
